/**
 * generator.js
 * Converts parsed metadata objects into Claude-ready Markdown skill files.
 */

'use strict';

/**
 * @param {string} metadataType  - e.g. 'objects', 'flows', 'classes'
 * @param {object} parsed        - output from the relevant parser
 * @param {object} config        - org-config.json contents
 * @returns {string}             - Markdown skill file content
 */
function generateSkill(metadataType, parsed, config) {
  const builders = {
    objects:        buildObjectsSkill,
    flows:          buildFlowsSkill,
    classes:        buildApexSkill,
    triggers:       buildApexSkill,
    lwc:            buildLwcSkill,
    permissionsets: buildPermsetSkill,
    profiles:       buildProfileSkill,
    layouts:        buildLayoutSkill,
    emailTemplates: buildTemplateSkill,
  };

  const builder = builders[metadataType];
  if (!builder) return `# ${metadataType}\n\nNo skill builder registered for this type.\n`;

  return builder(parsed, config);
}

// ─── BUILDERS ────────────────────────────────────────────────────────────────

function buildObjectsSkill(parsed, config) {
  const { objects = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Custom objects & fields
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when creating new custom objects, custom fields, or modifying object metadata to match this org's conventions.

## Naming conventions
`;

  // Derive naming patterns from real object names
  const prefixes = [...new Set(objects.map(o => o.apiName?.split('__')[0]).filter(Boolean))];
  if (prefixes.length) {
    md += `- **Namespace/prefix patterns found:** ${prefixes.join(', ')}\n`;
  }

  md += `- Custom objects end with \`__c\`\n`;
  md += `- Custom fields end with \`__c\`\n\n`;

  md += `## Objects in this org (${objects.length})\n\n`;

  for (const obj of objects) {
    md += `### ${obj.apiName || obj.label}\n`;
    if (obj.label)       md += `- **Label:** ${obj.label}\n`;
    if (obj.description) md += `- **Description:** ${obj.description}\n`;
    if (obj.fields?.length) {
      md += `- **Field count:** ${obj.fields.length}\n`;
      md += `- **Field types used:** ${[...new Set(obj.fields.map(f => f.type))].join(', ')}\n`;

      // Show up to 5 example fields
      const sample = obj.fields.slice(0, 5);
      md += `- **Sample fields:**\n`;
      for (const f of sample) {
        md += `  - \`${f.apiName}\` (${f.type})${f.required ? ' — required' : ''}\n`;
      }
    }
    md += '\n';
  }

  md += `## Design rules for new objects\n`;
  md += `- Mirror the naming prefix patterns listed above\n`;
  md += `- Always include a Description on new objects\n`;
  md += `- Required fields should be clearly marked\n`;
  md += `- Lookup fields should follow the pattern: \`RelatedObject__c\`\n`;

  return md;
}

function buildFlowsSkill(parsed, config) {
  const { flows = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Flows & automations
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when building new Flows, Screen Flows, or Record-Triggered Flows to match this org's structure and naming.

## Flow types in use\n`;

  const types = [...new Set(flows.map(f => f.processType).filter(Boolean))];
  for (const t of types) md += `- ${t}\n`;

  md += `\n## Naming patterns\n`;
  const names = flows.map(f => f.apiName || '').filter(Boolean);
  if (names.length) {
    md += `Examples from this org: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n\n`;
  }

  md += `## Flows inventory (${flows.length})\n\n`;
  for (const flow of flows) {
    md += `### ${flow.apiName}\n`;
    if (flow.label)       md += `- **Label:** ${flow.label}\n`;
    if (flow.processType) md += `- **Type:** ${flow.processType}\n`;
    if (flow.triggerType) md += `- **Trigger:** ${flow.triggerType}\n`;
    if (flow.object)      md += `- **Object:** ${flow.object}\n`;
    md += '\n';
  }

  md += `## Design rules for new flows\n`;
  md += `- Match the naming conventions shown above\n`;
  md += `- Record-triggered flows should specify trigger type (Before Save / After Save)\n`;
  md += `- Always add a description explaining the flow's business purpose\n`;
  md += `- Fault paths should be handled for all DML operations\n`;

  return md;
}

function buildApexSkill(parsed, config) {
  const { classes = [], triggers = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Apex classes & triggers
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when writing new Apex classes, trigger handlers, or test classes to match this org's code standards.

## Class naming conventions\n`;

  if (classes.length) {
    const names = classes.map(c => c.name).filter(Boolean);
    md += `Examples: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n\n`;

    // Detect patterns
    const hasHandler  = names.some(n => n.includes('Handler'));
    const hasService  = names.some(n => n.includes('Service'));
    const hasHelper   = names.some(n => n.includes('Helper'));
    const hasTest     = names.some(n => n.endsWith('Test') || n.endsWith('_Test'));

    if (hasHandler) md += `- Trigger handlers named: \`{Object}TriggerHandler\`\n`;
    if (hasService) md += `- Service classes named: \`{Domain}Service\`\n`;
    if (hasHelper)  md += `- Helper classes named: \`{Domain}Helper\`\n`;
    if (hasTest)    md += `- Test classes named: \`{ClassName}Test\`\n`;
  }

  md += `\n## Trigger conventions\n`;
  if (triggers.length) {
    for (const t of triggers) {
      md += `- \`${t.name}\` → object: ${t.object || 'unknown'}, events: ${t.events?.join(', ') || 'unknown'}\n`;
    }
  }

  md += `\n## Classes inventory (${classes.length})\n`;
  for (const cls of classes.slice(0, 20)) {
    md += `- \`${cls.name}\`${cls.isTest ? ' [test]' : ''}\n`;
  }
  if (classes.length > 20) md += `- ... and ${classes.length - 20} more\n`;

  md += `\n## Design rules for new Apex\n`;
  md += `- One trigger per object — all logic in a handler class\n`;
  md += `- Bulkify all trigger logic (never query or DML inside loops)\n`;
  md += `- Test classes must have @isTest annotation and achieve 90%+ coverage\n`;
  md += `- Use \`with sharing\` on all new classes unless explicitly required otherwise\n`;
  md += `- Constants go in a dedicated \`Constants\` or \`{Domain}Constants\` class\n`;

  return md;
}

function buildLwcSkill(parsed, config) {
  const { components = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: LWC components
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when building new Lightning Web Components to match this org's component structure and conventions.

## Component naming conventions
- camelCase for component folder and files\n`;

  if (components.length) {
    const names = components.map(c => c.name).filter(Boolean);
    md += `- Examples from this org: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n`;
  }

  md += `\n## Components inventory (${components.length})\n\n`;
  for (const cmp of components) {
    md += `### ${cmp.name}\n`;
    if (cmp.files?.length) md += `- **Files:** ${cmp.files.join(', ')}\n`;
    if (cmp.hasApexWire)   md += `- **Pattern:** Uses @wire with Apex\n`;
    if (cmp.hasLds)        md += `- **Pattern:** Uses Lightning Data Service\n`;
    md += '\n';
  }

  md += `## Design rules for new LWC\n`;
  md += `- Every component needs: .js, .html, .js-meta.xml\n`;
  md += `- Use @wire for read operations, imperative Apex for write operations\n`;
  md += `- Fire events upward, properties downward\n`;
  md += `- CSS scoped to component — no global styles\n`;

  return md;
}

function buildPermsetSkill(parsed, config) {
  const { permsets = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Permission sets
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when creating new permission sets to match this org's access model.

## Permission sets in this org (${permsets.length})\n\n`;

  for (const ps of permsets) {
    md += `### ${ps.label || ps.apiName}\n`;
    if (ps.description)       md += `- **Description:** ${ps.description}\n`;
    if (ps.objectPerms?.length) md += `- **Object permissions:** ${ps.objectPerms.length} objects\n`;
    if (ps.fieldPerms?.length)  md += `- **Field permissions:** ${ps.fieldPerms.length} fields\n`;
    md += '\n';
  }

  md += `## Design rules for new permission sets\n`;
  md += `- Always add a clear description explaining the business role\n`;
  md += `- Grant minimum required access — never grant Delete unless justified\n`;
  md += `- Field-level security must be explicitly set for sensitive fields\n`;

  return md;
}

function buildProfileSkill(parsed, config) {
  const { profiles = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Profiles
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when modifying profiles or understanding the org's user access model.

## Profiles in this org (${profiles.length})\n`;
  for (const p of profiles) md += `- \`${p.name}\`\n`;

  md += `\n## Design rules\n`;
  md += `- Prefer permission sets over profile permissions for feature access\n`;
  md += `- Profiles define baseline access; permission sets layer on top\n`;

  return md;
}

function buildLayoutSkill(parsed, config) {
  const { layouts = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Page layouts
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when creating or modifying page layouts.

## Layouts in this org (${layouts.length})\n`;
  for (const l of layouts) md += `- \`${l.name}\`\n`;

  md += `\n## Design rules\n`;
  md += `- Group related fields into sections\n`;
  md += `- Required fields should appear in the first section\n`;
  md += `- Use 2-column layout for standard sections\n`;

  return md;
}

function buildTemplateSkill(parsed, config) {
  const { templates = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Skill: Email templates
<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->

## When to use this skill
Load this skill when creating new email templates to match this org's tone and structure.

## Templates in this org (${templates.length})\n\n`;

  for (const t of templates) {
    md += `### ${t.name}\n`;
    if (t.subject)     md += `- **Subject pattern:** ${t.subject}\n`;
    if (t.encoding)    md += `- **Encoding:** ${t.encoding}\n`;
    md += '\n';
  }

  md += `## Design rules for new templates\n`;
  md += `- Use merge fields for personalization\n`;
  md += `- Always include a plain-text version\n`;
  md += `- Subject lines should be clear and action-oriented\n`;

  return md;
}

module.exports = { generateSkill };
