/**
 * generator.js
 * Converts parsed metadata into Claude Agent Skills (SKILL.md + references/)
 * for creatable metadata types, or plain reference Markdown for everything else.
 */

'use strict';

function frontmatter(name, description) {
  return `---\nname: ${name}\ndescription: ${description}\n---\n\n`;
}

const SKILL_REGISTRY = {
  objects:              { skillName: 'salesforce-objects',            builder: buildObjectsSkill },
  flows:                { skillName: 'salesforce-flows',              builder: buildFlowsSkill },
  classes:              { skillName: 'salesforce-apex',               builder: buildApexSkill },
  triggers:             { skillName: 'salesforce-apex',               builder: buildApexSkill },
  lwc:                  { skillName: 'salesforce-lwc',                builder: buildLwcSkill },
  permissionsets:       { skillName: 'salesforce-permission-sets',    builder: buildPermsetSkill },
  profiles:             { skillName: 'salesforce-profiles',           builder: buildProfileSkill },
  layouts:              { skillName: 'salesforce-layouts',            builder: buildLayoutSkill },
  emailTemplates:       { skillName: 'salesforce-email-templates',    builder: buildTemplateSkill },
  customMetadata:       { skillName: 'salesforce-custom-metadata',    builder: buildCustomMetadataSkill },
  connectedApps:        { skillName: 'salesforce-connected-apps',     builder: buildConnectedAppSkill },
  genAiPromptTemplates: { skillName: 'salesforce-prompt-templates',   builder: buildPromptTemplateSkill },
  flexipages:           { skillName: 'salesforce-flexipages',         builder: buildFlexipageSkill },
  approvalProcesses:    { skillName: 'salesforce-approval-processes', builder: buildApprovalProcessSkill },
};

function isSkillType(metadataType) {
  return Object.prototype.hasOwnProperty.call(SKILL_REGISTRY, metadataType);
}

function skillNameFor(metadataType) {
  const entry = SKILL_REGISTRY[metadataType];
  return entry ? entry.skillName : null;
}

/**
 * @param {string} metadataType - e.g. 'objects', 'flows', 'classes'
 * @param {object} parsed       - output from the relevant parser
 * @param {object} config       - org-config.json contents
 * @returns {{ skillMd: string, referenceMd: string }}
 */
function generateSkill(metadataType, parsed, config) {
  const entry = SKILL_REGISTRY[metadataType];
  if (!entry) {
    throw new Error(`No skill builder registered for metadata type: ${metadataType}`);
  }
  return entry.builder(parsed, config);
}

/**
 * @param {string} metadataType - any metadata type without a dedicated skill builder
 * @param {object} parsed       - output from parseGeneric: { items: [...] }
 * @param {object} config       - org-config.json contents
 * @returns {string} reference Markdown
 */
function generateReference(metadataType, parsed, config) {
  const { items = [] } = parsed;
  const now = new Date().toISOString().split('T')[0];

  let md = `# Reference: ${metadataType}\n`;
  md += `<!-- Generated by sf-claude-context-forge on ${now} for org: ${config.orgName} -->\n\n`;
  md += `Informational inventory only — not loaded as a Claude skill. ${items.length} item(s) found.\n\n`;

  for (const item of items) {
    md += `### ${item.fullName || item.apiName}\n`;
    if (item.label)       md += `- **Label:** ${item.label}\n`;
    if (item.description) md += `- **Description:** ${item.description}\n`;
    md += '\n';
  }

  return md;
}

// ─── TIER-1 BUILDERS ─────────────────────────────────────────────────────────

function buildObjectsSkill(parsed, config) {
  const { objects = [] } = parsed;
  const prefixes = [...new Set(objects.map(o => o.apiName?.split('__')[0]).filter(Boolean))];

  let skillMd = frontmatter(
    'salesforce-objects',
    'Conventions for creating custom objects and fields in this org. Use when creating or modifying Salesforce custom objects, custom fields, or object metadata.'
  );
  skillMd += `# Custom objects & fields\n\n## Naming conventions\n`;
  if (prefixes.length) skillMd += `- **Namespace/prefix patterns found:** ${prefixes.join(', ')}\n`;
  skillMd += `- Custom objects end with \`__c\`\n- Custom fields end with \`__c\`\n\n`;
  skillMd += `## Design rules for new objects\n`;
  skillMd += `- Mirror the naming prefix patterns listed above\n`;
  skillMd += `- Always include a Description on new objects\n`;
  skillMd += `- Required fields should be clearly marked\n`;
  skillMd += `- Lookup fields should follow the pattern: \`RelatedObject__c\`\n\n`;
  skillMd += `See \`references/objects-reference.md\` for the full inventory of objects and fields in this org.\n`;

  let referenceMd = `# Reference: Custom objects & fields (${objects.length})\n\n`;
  for (const obj of objects) {
    referenceMd += `### ${obj.apiName || obj.label}\n`;
    if (obj.label)       referenceMd += `- **Label:** ${obj.label}\n`;
    if (obj.description) referenceMd += `- **Description:** ${obj.description}\n`;
    if (obj.fields?.length) {
      referenceMd += `- **Field count:** ${obj.fields.length}\n`;
      referenceMd += `- **Field types used:** ${[...new Set(obj.fields.map(f => f.type))].join(', ')}\n`;
      referenceMd += `- **Sample fields:**\n`;
      for (const f of obj.fields.slice(0, 5)) {
        referenceMd += `  - \`${f.apiName}\` (${f.type})${f.required ? ' — required' : ''}\n`;
      }
    }
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildFlowsSkill(parsed, config) {
  const { flows = [] } = parsed;
  const types = [...new Set(flows.map(f => f.processType).filter(Boolean))];
  const names = flows.map(f => f.apiName || '').filter(Boolean);

  let skillMd = frontmatter(
    'salesforce-flows',
    "Conventions for building Flows in this org. Use when creating new Flows, Screen Flows, or Record-Triggered Flows."
  );
  skillMd += `# Flows & automations\n\n## Flow types in use\n`;
  for (const t of types) skillMd += `- ${t}\n`;
  skillMd += `\n## Naming patterns\n`;
  if (names.length) skillMd += `Examples from this org: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n\n`;
  skillMd += `## Design rules for new flows\n`;
  skillMd += `- Match the naming conventions shown above\n`;
  skillMd += `- Record-triggered flows should specify trigger type (Before Save / After Save)\n`;
  skillMd += `- Always add a description explaining the flow's business purpose\n`;
  skillMd += `- Fault paths should be handled for all DML operations\n\n`;
  skillMd += `See \`references/flows-reference.md\` for the full flow inventory.\n`;

  let referenceMd = `# Reference: Flows & automations (${flows.length})\n\n`;
  for (const flow of flows) {
    referenceMd += `### ${flow.apiName}\n`;
    if (flow.label)       referenceMd += `- **Label:** ${flow.label}\n`;
    if (flow.processType) referenceMd += `- **Type:** ${flow.processType}\n`;
    if (flow.triggerType) referenceMd += `- **Trigger:** ${flow.triggerType}\n`;
    if (flow.object)      referenceMd += `- **Object:** ${flow.object}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildApexSkill(parsed, config) {
  const { classes = [], triggers = [] } = parsed;
  const names = classes.map(c => c.name).filter(Boolean);

  let skillMd = frontmatter(
    'salesforce-apex',
    'Conventions for writing Apex classes and triggers in this org. Use when writing new Apex classes, trigger handlers, or test classes.'
  );
  skillMd += `# Apex classes & triggers\n\n## Class naming conventions\n`;
  if (names.length) {
    skillMd += `Examples: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n\n`;
    if (names.some(n => n.includes('Handler'))) skillMd += `- Trigger handlers named: \`{Object}TriggerHandler\`\n`;
    if (names.some(n => n.includes('Service'))) skillMd += `- Service classes named: \`{Domain}Service\`\n`;
    if (names.some(n => n.includes('Helper')))  skillMd += `- Helper classes named: \`{Domain}Helper\`\n`;
    if (names.some(n => n.endsWith('Test') || n.endsWith('_Test'))) skillMd += `- Test classes named: \`{ClassName}Test\`\n`;
  }
  skillMd += `\n## Trigger conventions\n`;
  for (const t of triggers) {
    skillMd += `- \`${t.name}\` → object: ${t.object || 'unknown'}, events: ${t.events?.join(', ') || 'unknown'}\n`;
  }
  skillMd += `\n## Design rules for new Apex\n`;
  skillMd += `- One trigger per object — all logic in a handler class\n`;
  skillMd += `- Bulkify all trigger logic (never query or DML inside loops)\n`;
  skillMd += `- Test classes must have @isTest annotation and achieve 90%+ coverage\n`;
  skillMd += `- Use \`with sharing\` on all new classes unless explicitly required otherwise\n`;
  skillMd += `- Constants go in a dedicated \`Constants\` or \`{Domain}Constants\` class\n\n`;
  skillMd += `See \`references/apex-reference.md\` for the full class/trigger inventory.\n`;

  let referenceMd = `# Reference: Apex classes & triggers (${classes.length} classes, ${triggers.length} triggers)\n\n## Classes\n`;
  for (const cls of classes) referenceMd += `- \`${cls.name}\`${cls.isTest ? ' [test]' : ''}\n`;
  referenceMd += `\n## Triggers\n`;
  for (const t of triggers) referenceMd += `- \`${t.name}\` → object: ${t.object || 'unknown'}, events: ${t.events?.join(', ') || 'unknown'}\n`;

  return { skillMd, referenceMd };
}

function buildLwcSkill(parsed, config) {
  const { components = [] } = parsed;
  const names = components.map(c => c.name).filter(Boolean);

  let skillMd = frontmatter(
    'salesforce-lwc',
    'Conventions for building Lightning Web Components in this org. Use when creating new LWC components.'
  );
  skillMd += `# LWC components\n\n## Component naming conventions\n- camelCase for component folder and files\n`;
  if (names.length) skillMd += `- Examples from this org: ${names.slice(0, 8).map(n => `\`${n}\``).join(', ')}\n`;
  skillMd += `\n## Design rules for new LWC\n`;
  skillMd += `- Every component needs: .js, .html, .js-meta.xml\n`;
  skillMd += `- Use @wire for read operations, imperative Apex for write operations\n`;
  skillMd += `- Fire events upward, properties downward\n`;
  skillMd += `- CSS scoped to component — no global styles\n\n`;
  skillMd += `See \`references/lwc-reference.md\` for the full component inventory.\n`;

  let referenceMd = `# Reference: LWC components (${components.length})\n\n`;
  for (const cmp of components) {
    referenceMd += `### ${cmp.name}\n`;
    if (cmp.files?.length) referenceMd += `- **Files:** ${cmp.files.join(', ')}\n`;
    if (cmp.hasApexWire)   referenceMd += `- **Pattern:** Uses @wire with Apex\n`;
    if (cmp.hasLds)        referenceMd += `- **Pattern:** Uses Lightning Data Service\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildPermsetSkill(parsed, config) {
  const { permsets = [] } = parsed;

  let skillMd = frontmatter(
    'salesforce-permission-sets',
    "Conventions for this org's access model. Use when creating new permission sets."
  );
  skillMd += `# Permission sets\n\n## Design rules for new permission sets\n`;
  skillMd += `- Always add a clear description explaining the business role\n`;
  skillMd += `- Grant minimum required access — never grant Delete unless justified\n`;
  skillMd += `- Field-level security must be explicitly set for sensitive fields\n\n`;
  skillMd += `See \`references/permission-sets-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Permission sets (${permsets.length})\n\n`;
  for (const ps of permsets) {
    referenceMd += `### ${ps.label || ps.apiName}\n`;
    if (ps.description)         referenceMd += `- **Description:** ${ps.description}\n`;
    if (ps.objectPerms?.length) referenceMd += `- **Object permissions:** ${ps.objectPerms.length} objects\n`;
    if (ps.fieldPerms?.length)  referenceMd += `- **Field permissions:** ${ps.fieldPerms.length} fields\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildProfileSkill(parsed, config) {
  const { profiles = [] } = parsed;

  let skillMd = frontmatter(
    'salesforce-profiles',
    "This org's user access model. Use when modifying profiles or reasoning about baseline user access."
  );
  skillMd += `# Profiles\n\n## Design rules\n`;
  skillMd += `- Prefer permission sets over profile permissions for feature access\n`;
  skillMd += `- Profiles define baseline access; permission sets layer on top\n\n`;
  skillMd += `See \`references/profiles-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Profiles (${profiles.length})\n\n`;
  for (const p of profiles) referenceMd += `- \`${p.name}\`\n`;

  return { skillMd, referenceMd };
}

function buildLayoutSkill(parsed, config) {
  const { layouts = [] } = parsed;

  let skillMd = frontmatter(
    'salesforce-layouts',
    'Conventions for page layouts in this org. Use when creating or modifying page layouts.'
  );
  skillMd += `# Page layouts\n\n## Design rules\n`;
  skillMd += `- Group related fields into sections\n`;
  skillMd += `- Required fields should appear in the first section\n`;
  skillMd += `- Use 2-column layout for standard sections\n\n`;
  skillMd += `See \`references/layouts-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Page layouts (${layouts.length})\n\n`;
  for (const l of layouts) referenceMd += `- \`${l.name}\`\n`;

  return { skillMd, referenceMd };
}

function buildTemplateSkill(parsed, config) {
  const { templates = [] } = parsed;

  let skillMd = frontmatter(
    'salesforce-email-templates',
    "Conventions for this org's email templates. Use when creating new email templates."
  );
  skillMd += `# Email templates\n\n## Design rules for new templates\n`;
  skillMd += `- Use merge fields for personalization\n`;
  skillMd += `- Always include a plain-text version\n`;
  skillMd += `- Subject lines should be clear and action-oriented\n\n`;
  skillMd += `See \`references/email-templates-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Email templates (${templates.length})\n\n`;
  for (const t of templates) {
    referenceMd += `### ${t.name}\n`;
    if (t.subject)  referenceMd += `- **Subject pattern:** ${t.subject}\n`;
    if (t.encoding) referenceMd += `- **Encoding:** ${t.encoding}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildCustomMetadataSkill(parsed, config) {
  const { records = [] } = parsed;
  const typeNames = [...new Set(records.map(r => r.typeName).filter(Boolean))];

  let skillMd = frontmatter(
    'salesforce-custom-metadata',
    "Conventions for this org's Custom Metadata Types. Use when creating new custom metadata type records."
  );
  skillMd += `# Custom Metadata\n\n## Custom Metadata Types in use\n`;
  for (const t of typeNames) skillMd += `- \`${t}\`\n`;
  skillMd += `\n## Design rules for new records\n`;
  skillMd += `- Record names should describe the configuration they hold, not the type\n`;
  skillMd += `- Mark records \`protected\` only when they should not be visible to subscriber orgs\n`;
  skillMd += `- Prefer Custom Metadata over Custom Settings for new configuration — it's deployable and queryable\n\n`;
  skillMd += `See \`references/custom-metadata-reference.md\` for the full record inventory.\n`;

  let referenceMd = `# Reference: Custom Metadata records (${records.length})\n\n`;
  for (const r of records) {
    referenceMd += `### ${r.fullName}\n`;
    if (r.label) referenceMd += `- **Label:** ${r.label}\n`;
    referenceMd += `- **Type:** ${r.typeName}\n- **Protected:** ${r.protected}\n`;
    if (r.fields?.length) {
      referenceMd += `- **Fields:**\n`;
      for (const f of r.fields) referenceMd += `  - \`${f.field}\` = ${f.value}\n`;
    }
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildConnectedAppSkill(parsed, config) {
  const { apps = [] } = parsed;
  const allScopes = [...new Set(apps.flatMap(a => a.scopes || []))];

  let skillMd = frontmatter(
    'salesforce-connected-apps',
    "Conventions for this org's Connected Apps. Use when creating a new Connected App for an integration."
  );
  skillMd += `# Connected Apps\n\n## OAuth scopes commonly used in this org\n`;
  for (const s of allScopes) skillMd += `- ${s}\n`;
  skillMd += `\n## Design rules for new connected apps\n`;
  skillMd += `- Request the minimum OAuth scopes needed for the integration\n`;
  skillMd += `- Always set a contact email for ownership traceability\n`;
  skillMd += `- Prefer named credentials / external client apps over storing secrets in Apex\n\n`;
  skillMd += `See \`references/connected-apps-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Connected Apps (${apps.length})\n\n`;
  for (const a of apps) {
    referenceMd += `### ${a.label || a.apiName}\n`;
    if (a.description)    referenceMd += `- **Description:** ${a.description}\n`;
    if (a.contactEmail)   referenceMd += `- **Contact email:** ${a.contactEmail}\n`;
    if (a.scopes?.length)  referenceMd += `- **Scopes:** ${a.scopes.join(', ')}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildPromptTemplateSkill(parsed, config) {
  const { templates = [] } = parsed;
  const templateTypes = [...new Set(templates.map(t => t.templateType).filter(Boolean))];

  let skillMd = frontmatter(
    'salesforce-prompt-templates',
    "Conventions for this org's Prompt Builder / GenAI prompt templates. Use when creating a new Agentforce or Prompt Builder template."
  );
  skillMd += `# Prompt templates (Prompt Builder / Agentforce)\n\n## Template types in use\n`;
  for (const t of templateTypes) skillMd += `- ${t}\n`;
  skillMd += `\n## Design rules for new prompt templates\n`;
  skillMd += `- Keep grounding/merge-field references explicit and scoped to the fields actually needed\n`;
  skillMd += `- Give every template a description explaining its business purpose\n`;
  skillMd += `- Test each template version before activating it\n\n`;
  skillMd += `See \`references/prompt-templates-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Prompt templates (${templates.length})\n\n`;
  for (const t of templates) {
    referenceMd += `### ${t.masterLabel || t.apiName}\n`;
    if (t.templateType) referenceMd += `- **Type:** ${t.templateType}\n`;
    if (t.description)  referenceMd += `- **Description:** ${t.description}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildFlexipageSkill(parsed, config) {
  const { pages = [] } = parsed;
  const pageTypes = [...new Set(pages.map(p => p.type).filter(Boolean))];

  let skillMd = frontmatter(
    'salesforce-flexipages',
    "Conventions for this org's Lightning pages (FlexiPages). Use when creating a new App Page, Record Page, or Home Page."
  );
  skillMd += `# FlexiPages (Lightning App Builder)\n\n## Page types in use\n`;
  for (const t of pageTypes) skillMd += `- ${t}\n`;
  skillMd += `\n## Design rules for new pages\n`;
  skillMd += `- Name pages by their purpose and object, e.g. \`{Object}_Record_Page\`\n`;
  skillMd += `- Record pages should declare the \`sobjectType\` they target\n`;
  skillMd += `- Reuse existing components before building new custom ones\n\n`;
  skillMd += `See \`references/flexipages-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: FlexiPages (${pages.length})\n\n`;
  for (const p of pages) {
    referenceMd += `### ${p.masterLabel || p.apiName}\n`;
    if (p.type)        referenceMd += `- **Type:** ${p.type}\n`;
    if (p.sobjectType) referenceMd += `- **Object:** ${p.sobjectType}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

function buildApprovalProcessSkill(parsed, config) {
  const { processes = [] } = parsed;
  const entities = [...new Set(processes.map(p => p.entity).filter(Boolean))];

  let skillMd = frontmatter(
    'salesforce-approval-processes',
    "Conventions for this org's Approval Processes. Use when creating a new approval process."
  );
  skillMd += `# Approval Processes\n\n## Objects with approval processes\n`;
  for (const e of entities) skillMd += `- ${e}\n`;
  skillMd += `\n## Design rules for new approval processes\n`;
  skillMd += `- Give every process a description explaining when it triggers and why\n`;
  skillMd += `- Define an explicit rejection/recall path, not just the approval path\n`;
  skillMd += `- Keep entry criteria narrow enough to avoid unintended submissions\n\n`;
  skillMd += `See \`references/approval-processes-reference.md\` for the full inventory.\n`;

  let referenceMd = `# Reference: Approval Processes (${processes.length})\n\n`;
  for (const p of processes) {
    referenceMd += `### ${p.fullName}\n`;
    if (p.label) referenceMd += `- **Label:** ${p.label}\n`;
    referenceMd += `- **Object:** ${p.entity}\n- **Active:** ${p.active}\n`;
    if (p.description) referenceMd += `- **Description:** ${p.description}\n`;
    referenceMd += '\n';
  }

  return { skillMd, referenceMd };
}

module.exports = { generateSkill, generateReference, isSkillType, skillNameFor };
