"""
generator.py
Converts parsed metadata dicts into Claude-ready Markdown skill files.
"""

from datetime import date


def generate_skill(metadata_type: str, parsed: dict, config: dict) -> str:
    builders = {
        "objects":        _build_objects,
        "flows":          _build_flows,
        "classes":        _build_apex,
        "triggers":       _build_apex,
        "lwc":            _build_lwc,
        "permissionsets": _build_permsets,
        "profiles":       _build_profiles,
        "layouts":        _build_layouts,
        "emailTemplates": _build_templates,
    }
    builder = builders.get(metadata_type)
    if not builder:
        return f"# {metadata_type}\n\nNo skill builder registered for this type.\n"
    return builder(parsed, config)


def _today() -> str:
    return date.today().isoformat()


def _build_objects(parsed: dict, config: dict) -> str:
    objects = parsed.get("objects", [])
    now     = _today()
    lines   = [
        f"# Skill: Custom objects & fields",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "",
        "## When to use this skill",
        "Load this skill when creating new custom objects, custom fields, or modifying object metadata.",
        "",
        "## Naming conventions",
        "- Custom objects end with `__c`",
        "- Custom fields end with `__c`",
        "",
        f"## Objects in this org ({len(objects)})",
        "",
    ]
    for obj in objects:
        lines.append(f"### {obj.get('apiName', obj.get('label', 'Unknown'))}")
        if obj.get("label"):       lines.append(f"- **Label:** {obj['label']}")
        if obj.get("description"): lines.append(f"- **Description:** {obj['description']}")
        fields = obj.get("fields", [])
        if fields:
            types = list({f.get("type") for f in fields if f.get("type")})
            lines.append(f"- **Field types used:** {', '.join(types)}")
            lines.append("- **Sample fields:**")
            for f in fields[:5]:
                req = " — required" if f.get("required") else ""
                lines.append(f"  - `{f['apiName']}` ({f.get('type', '?')}){req}")
        lines.append("")
    lines += [
        "## Design rules for new objects",
        "- Mirror existing naming prefix patterns",
        "- Always include a Description on new objects",
        "- Required fields should be clearly marked",
    ]
    return "\n".join(lines)


def _build_flows(parsed: dict, config: dict) -> str:
    flows = parsed.get("flows", [])
    now   = _today()
    types = list({f.get("processType") for f in flows if f.get("processType")})
    lines = [
        "# Skill: Flows & automations",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "",
        "## When to use this skill",
        "Load this skill when building new Flows or Record-Triggered Flows.",
        "",
        "## Flow types in use",
    ] + [f"- {t}" for t in types] + ["", f"## Flows inventory ({len(flows)})", ""]
    for flow in flows:
        lines.append(f"### {flow.get('apiName', 'Unknown')}")
        if flow.get("label"):       lines.append(f"- **Label:** {flow['label']}")
        if flow.get("processType"): lines.append(f"- **Type:** {flow['processType']}")
        if flow.get("triggerType"): lines.append(f"- **Trigger:** {flow['triggerType']}")
        if flow.get("object"):      lines.append(f"- **Object:** {flow['object']}")
        lines.append("")
    lines += [
        "## Design rules for new flows",
        "- Match existing naming conventions",
        "- Always handle fault paths for DML operations",
        "- Add a description explaining the business purpose",
    ]
    return "\n".join(lines)


def _build_apex(parsed: dict, config: dict) -> str:
    classes  = parsed.get("classes", [])
    triggers = parsed.get("triggers", [])
    now      = _today()
    lines    = [
        "# Skill: Apex classes & triggers",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "",
        "## When to use this skill",
        "Load this skill when writing Apex classes, trigger handlers, or test classes.",
        "",
        f"## Classes ({len(classes)})",
    ]
    for cls in classes[:20]:
        tag = " [test]" if cls.get("isTest") else ""
        lines.append(f"- `{cls['name']}`{tag}")
    if len(classes) > 20:
        lines.append(f"- ... and {len(classes) - 20} more")
    lines += ["", f"## Triggers ({len(triggers)})"]
    for t in triggers:
        lines.append(f"- `{t['name']}` → {t.get('object','?')} ({', '.join(t.get('events',[]))})")
    lines += [
        "",
        "## Design rules",
        "- One trigger per object — handler class pattern",
        "- Bulkify all DML and queries",
        "- Test classes must reach 90%+ coverage",
        "- Use `with sharing` on all new classes",
    ]
    return "\n".join(lines)


def _build_lwc(parsed: dict, config: dict) -> str:
    components = parsed.get("components", [])
    now        = _today()
    lines      = [
        "# Skill: LWC components",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "",
        "## When to use this skill",
        "Load this skill when building new Lightning Web Components.",
        "",
        f"## Components ({len(components)})",
        "",
    ]
    for cmp in components:
        lines.append(f"### {cmp['name']}")
        if cmp.get("hasApexWire"): lines.append("- Uses @wire with Apex")
        if cmp.get("hasLds"):      lines.append("- Uses Lightning Data Service")
        lines.append("")
    lines += [
        "## Design rules",
        "- Every component needs .js, .html, .js-meta.xml",
        "- @wire for reads, imperative for writes",
        "- Events up, properties down",
    ]
    return "\n".join(lines)


def _build_permsets(parsed, config):
    ps_list = parsed.get("permsets", [])
    now = _today()
    lines = [
        "# Skill: Permission sets",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "", "## Permission sets", "",
    ]
    for ps in ps_list:
        lines.append(f"### {ps.get('label') or ps.get('apiName')}")
        if ps.get("description"): lines.append(f"- {ps['description']}")
        lines.append("")
    lines += ["## Design rules", "- Minimum required access", "- Always add a description"]
    return "\n".join(lines)


def _build_profiles(parsed, config):
    profiles = parsed.get("profiles", [])
    now = _today()
    lines = [
        "# Skill: Profiles",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "", f"## Profiles ({len(profiles)})",
    ] + [f"- `{p['name']}`" for p in profiles]
    lines += ["", "## Design rules", "- Use permission sets for feature access", "- Profiles define baseline only"]
    return "\n".join(lines)


def _build_layouts(parsed, config):
    layouts = parsed.get("layouts", [])
    now = _today()
    lines = [
        "# Skill: Page layouts",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "", f"## Layouts ({len(layouts)})",
    ] + [f"- `{l['name']}`" for l in layouts]
    lines += ["", "## Design rules", "- Group related fields into sections", "- 2-column layout for standard sections"]
    return "\n".join(lines)


def _build_templates(parsed, config):
    templates = parsed.get("templates", [])
    now = _today()
    lines = [
        "# Skill: Email templates",
        f"<!-- Generated by sf-claude-context-forge on {now} for org: {config['orgName']} -->",
        "", f"## Templates ({len(templates)})", "",
    ]
    for t in templates:
        lines.append(f"### {t['name']}")
        if t.get("subject"): lines.append(f"- Subject: {t['subject']}")
        lines.append("")
    lines += ["## Design rules", "- Use merge fields for personalization", "- Always include plain-text version"]
    return "\n".join(lines)
