"""
generator.py
Converts parsed metadata into Claude Agent Skills (SKILL.md + references/)
for creatable metadata types, or plain reference Markdown for everything else.
Port of scripts/node/generator.js.
"""

from datetime import date


def _frontmatter(name: str, description: str) -> str:
    return f'---\nname: {name}\ndescription: {description}\n---\n\n'


def is_skill_type(metadata_type: str) -> bool:
    """True if metadata_type has a dedicated Tier-1 skill builder."""
    return metadata_type in _SKILL_REGISTRY


def skill_name_for(metadata_type: str) -> str | None:
    """The .claude/skills/<name> directory name for a Tier-1 metadata type."""
    entry = _SKILL_REGISTRY.get(metadata_type)
    return entry['skillName'] if entry else None


def generate_skill(metadata_type: str, parsed: dict, config: dict) -> dict:
    """
    Generate a Tier-1 skill (SKILL.md + reference Markdown) for a creatable type.

    Returns:
        {'skillMd': str, 'referenceMd': str}
    """
    entry = _SKILL_REGISTRY.get(metadata_type)
    if not entry:
        raise ValueError(f'No skill builder registered for metadata type: {metadata_type}')
    return entry['builder'](parsed, config)


def generate_reference(metadata_type: str, parsed: dict, config: dict) -> str:
    """Generate a Tier-2 plain-reference Markdown doc for a non-creatable metadata type."""
    items = parsed.get('items', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        f'# Reference: {metadata_type}',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        f'Informational inventory only — not loaded as a Claude skill. {len(items)} item(s) found.',
        '',
    ]

    for item in items:
        lines.append(f"### {item.get('fullName') or item.get('apiName', '')}")
        if item.get('label'):
            lines.append(f"- **Label:** {item['label']}")
        if item.get('description'):
            lines.append(f"- **Description:** {item['description']}")
        lines.append('')

    return '\n'.join(lines) + '\n'


# ─── TIER-1 BUILDERS ─────────────────────────────────────────────────────────

def _build_objects_skill(parsed: dict, config: dict) -> dict:
    objects = parsed.get('objects', [])
    prefixes = list(dict.fromkeys(
        o['apiName'].split('__')[0] for o in objects if o.get('apiName') and '__' in o['apiName']
    ))

    skill_lines = [_frontmatter(
        'salesforce-objects',
        'Conventions for creating custom objects and fields in this org. Use when creating or '
        'modifying Salesforce custom objects, custom fields, or object metadata.'
    ).rstrip('\n'), '', '# Custom objects & fields', '', '## Naming conventions']
    if prefixes:
        skill_lines.append(f"- **Namespace/prefix patterns found:** {', '.join(prefixes)}")
    skill_lines += [
        '- Custom objects end with `__c`',
        '- Custom fields end with `__c`',
        '',
        '## Design rules for new objects',
        '- Mirror the naming prefix patterns listed above',
        '- Always include a Description on new objects',
        '- Required fields should be clearly marked',
        '- Lookup fields should follow the pattern: `RelatedObject__c`',
        '',
        'See `references/objects-reference.md` for the full inventory of objects and fields in this org.',
    ]

    ref_lines = [f'# Reference: Custom objects & fields ({len(objects)})', '']
    for obj in objects:
        ref_lines.append(f"### {obj.get('apiName') or obj.get('label', '')}")
        if obj.get('label'):
            ref_lines.append(f"- **Label:** {obj['label']}")
        if obj.get('description'):
            ref_lines.append(f"- **Description:** {obj['description']}")
        fields = obj.get('fields', [])
        if fields:
            field_types = list(dict.fromkeys(f['type'] for f in fields if f.get('type')))
            ref_lines.append(f"- **Field count:** {len(fields)}")
            ref_lines.append(f"- **Field types used:** {', '.join(field_types)}")
            ref_lines.append('- **Sample fields:**')
            for f in fields[:5]:
                req = ' — required' if f.get('required') else ''
                ref_lines.append(f"  - `{f['apiName']}` ({f.get('type', '')}){req}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_flows_skill(parsed: dict, config: dict) -> dict:
    flows = parsed.get('flows', [])
    types = list(dict.fromkeys(f['processType'] for f in flows if f.get('processType')))
    names = [f['apiName'] for f in flows if f.get('apiName')]

    skill_lines = [_frontmatter(
        'salesforce-flows',
        'Conventions for building Flows in this org. Use when creating new Flows, Screen Flows, or Record-Triggered Flows.'
    ).rstrip('\n'), '', '# Flows & automations', '', '## Flow types in use']
    skill_lines += [f'- {t}' for t in types]
    skill_lines += ['', '## Naming patterns']
    if names:
        skill_lines.append(f"Examples from this org: {', '.join(f'`{n}`' for n in names[:8])}")
    skill_lines += [
        '',
        '## Design rules for new flows',
        '- Match the naming conventions shown above',
        '- Record-triggered flows should specify trigger type (Before Save / After Save)',
        "- Always add a description explaining the flow's business purpose",
        '- Fault paths should be handled for all DML operations',
        '',
        'See `references/flows-reference.md` for the full flow inventory.',
    ]

    ref_lines = [f'# Reference: Flows & automations ({len(flows)})', '']
    for flow in flows:
        ref_lines.append(f"### {flow.get('apiName', '')}")
        if flow.get('label'):
            ref_lines.append(f"- **Label:** {flow['label']}")
        if flow.get('processType'):
            ref_lines.append(f"- **Type:** {flow['processType']}")
        if flow.get('triggerType'):
            ref_lines.append(f"- **Trigger:** {flow['triggerType']}")
        if flow.get('object'):
            ref_lines.append(f"- **Object:** {flow['object']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_apex_skill(parsed: dict, config: dict) -> dict:
    classes = parsed.get('classes', [])
    triggers = parsed.get('triggers', [])
    names = [c['name'] for c in classes if c.get('name')]

    skill_lines = [_frontmatter(
        'salesforce-apex',
        'Conventions for writing Apex classes and triggers in this org. Use when writing new Apex classes, trigger handlers, or test classes.'
    ).rstrip('\n'), '', '# Apex classes & triggers', '', '## Class naming conventions']
    if names:
        skill_lines.append(f"Examples: {', '.join(f'`{n}`' for n in names[:8])}")
        skill_lines.append('')
        if any('Handler' in n for n in names):
            skill_lines.append('- Trigger handlers named: `{Object}TriggerHandler`')
        if any('Service' in n for n in names):
            skill_lines.append('- Service classes named: `{Domain}Service`')
        if any('Helper' in n for n in names):
            skill_lines.append('- Helper classes named: `{Domain}Helper`')
        if any(n.endswith('Test') or n.endswith('_Test') for n in names):
            skill_lines.append('- Test classes named: `{ClassName}Test`')
    skill_lines += ['', '## Trigger conventions']
    for t in triggers:
        events = ', '.join(t.get('events', [])) or 'unknown'
        skill_lines.append(f"- `{t['name']}` → object: {t.get('object') or 'unknown'}, events: {events}")
    skill_lines += [
        '',
        '## Design rules for new Apex',
        '- One trigger per object — all logic in a handler class',
        '- Bulkify all trigger logic (never query or DML inside loops)',
        '- Test classes must have @isTest annotation and achieve 90%+ coverage',
        '- Use `with sharing` on all new classes unless explicitly required otherwise',
        '- Constants go in a dedicated `Constants` or `{Domain}Constants` class',
        '',
        'See `references/apex-reference.md` for the full class/trigger inventory.',
    ]

    ref_lines = [f'# Reference: Apex classes & triggers ({len(classes)} classes, {len(triggers)} triggers)', '', '## Classes']
    for cls in classes:
        test_tag = ' [test]' if cls.get('isTest') else ''
        ref_lines.append(f"- `{cls['name']}`{test_tag}")
    ref_lines += ['', '## Triggers']
    for t in triggers:
        events = ', '.join(t.get('events', [])) or 'unknown'
        ref_lines.append(f"- `{t['name']}` → object: {t.get('object') or 'unknown'}, events: {events}")

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_lwc_skill(parsed: dict, config: dict) -> dict:
    components = parsed.get('components', [])
    names = [c['name'] for c in components if c.get('name')]

    skill_lines = [_frontmatter(
        'salesforce-lwc',
        'Conventions for building Lightning Web Components in this org. Use when creating new LWC components.'
    ).rstrip('\n'), '', '# LWC components', '', '## Component naming conventions', '- camelCase for component folder and files']
    if names:
        skill_lines.append(f"- Examples from this org: {', '.join(f'`{n}`' for n in names[:8])}")
    skill_lines += [
        '',
        '## Design rules for new LWC',
        '- Every component needs: .js, .html, .js-meta.xml',
        '- Use @wire for read operations, imperative Apex for write operations',
        '- Fire events upward, properties downward',
        '- CSS scoped to component — no global styles',
        '',
        'See `references/lwc-reference.md` for the full component inventory.',
    ]

    ref_lines = [f'# Reference: LWC components ({len(components)})', '']
    for cmp in components:
        ref_lines.append(f"### {cmp['name']}")
        if cmp.get('files'):
            ref_lines.append(f"- **Files:** {', '.join(cmp['files'])}")
        if cmp.get('hasApexWire'):
            ref_lines.append('- **Pattern:** Uses @wire with Apex')
        if cmp.get('hasLds'):
            ref_lines.append('- **Pattern:** Uses Lightning Data Service')
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_permset_skill(parsed: dict, config: dict) -> dict:
    permsets = parsed.get('permsets', [])

    skill_lines = [_frontmatter(
        'salesforce-permission-sets',
        "Conventions for this org's access model. Use when creating new permission sets."
    ).rstrip('\n'), '', '# Permission sets', '', '## Design rules for new permission sets',
        '- Always add a clear description explaining the business role',
        '- Grant minimum required access — never grant Delete unless justified',
        '- Field-level security must be explicitly set for sensitive fields',
        '',
        'See `references/permission-sets-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Permission sets ({len(permsets)})', '']
    for ps in permsets:
        ref_lines.append(f"### {ps.get('label') or ps.get('apiName', '')}")
        if ps.get('description'):
            ref_lines.append(f"- **Description:** {ps['description']}")
        if ps.get('objectPerms'):
            ref_lines.append(f"- **Object permissions:** {len(ps['objectPerms'])} objects")
        if ps.get('fieldPerms'):
            ref_lines.append(f"- **Field permissions:** {len(ps['fieldPerms'])} fields")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_profile_skill(parsed: dict, config: dict) -> dict:
    profiles = parsed.get('profiles', [])

    skill_lines = [_frontmatter(
        'salesforce-profiles',
        "This org's user access model. Use when modifying profiles or reasoning about baseline user access."
    ).rstrip('\n'), '', '# Profiles', '', '## Design rules',
        '- Prefer permission sets over profile permissions for feature access',
        '- Profiles define baseline access; permission sets layer on top',
        '',
        'See `references/profiles-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Profiles ({len(profiles)})']
    for p in profiles:
        ref_lines.append(f"- `{p['name']}`")

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_layout_skill(parsed: dict, config: dict) -> dict:
    layouts = parsed.get('layouts', [])

    skill_lines = [_frontmatter(
        'salesforce-layouts',
        'Conventions for page layouts in this org. Use when creating or modifying page layouts.'
    ).rstrip('\n'), '', '# Page layouts', '', '## Design rules',
        '- Group related fields into sections',
        '- Required fields should appear in the first section',
        '- Use 2-column layout for standard sections',
        '',
        'See `references/layouts-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Page layouts ({len(layouts)})']
    for l in layouts:
        ref_lines.append(f"- `{l['name']}`")

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_template_skill(parsed: dict, config: dict) -> dict:
    templates = parsed.get('templates', [])

    skill_lines = [_frontmatter(
        'salesforce-email-templates',
        "Conventions for this org's email templates. Use when creating new email templates."
    ).rstrip('\n'), '', '# Email templates', '', '## Design rules for new templates',
        '- Use merge fields for personalization',
        '- Always include a plain-text version',
        '- Subject lines should be clear and action-oriented',
        '',
        'See `references/email-templates-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Email templates ({len(templates)})', '']
    for t in templates:
        ref_lines.append(f"### {t['name']}")
        if t.get('subject'):
            ref_lines.append(f"- **Subject pattern:** {t['subject']}")
        if t.get('encoding'):
            ref_lines.append(f"- **Encoding:** {t['encoding']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_custom_metadata_skill(parsed: dict, config: dict) -> dict:
    records = parsed.get('records', [])
    type_names = list(dict.fromkeys(r['typeName'] for r in records if r.get('typeName')))

    skill_lines = [_frontmatter(
        'salesforce-custom-metadata',
        "Conventions for this org's Custom Metadata Types. Use when creating new custom metadata type records."
    ).rstrip('\n'), '', '# Custom Metadata', '', '## Custom Metadata Types in use']
    skill_lines += [f'- `{t}`' for t in type_names]
    skill_lines += [
        '',
        '## Design rules for new records',
        '- Record names should describe the configuration they hold, not the type',
        '- Mark records `protected` only when they should not be visible to subscriber orgs',
        "- Prefer Custom Metadata over Custom Settings for new configuration — it's deployable and queryable",
        '',
        'See `references/custom-metadata-reference.md` for the full record inventory.',
    ]

    ref_lines = [f'# Reference: Custom Metadata records ({len(records)})', '']
    for r in records:
        ref_lines.append(f"### {r['fullName']}")
        if r.get('label'):
            ref_lines.append(f"- **Label:** {r['label']}")
        ref_lines.append(f"- **Type:** {r['typeName']}")
        ref_lines.append(f"- **Protected:** {r['protected']}")
        if r.get('fields'):
            ref_lines.append('- **Fields:**')
            for f in r['fields']:
                ref_lines.append(f"  - `{f['field']}` = {f['value']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_connected_app_skill(parsed: dict, config: dict) -> dict:
    apps = parsed.get('apps', [])
    all_scopes = list(dict.fromkeys(s for a in apps for s in a.get('scopes', [])))

    skill_lines = [_frontmatter(
        'salesforce-connected-apps',
        "Conventions for this org's Connected Apps. Use when creating a new Connected App for an integration."
    ).rstrip('\n'), '', '# Connected Apps', '', '## OAuth scopes commonly used in this org']
    skill_lines += [f'- {s}' for s in all_scopes]
    skill_lines += [
        '',
        '## Design rules for new connected apps',
        '- Request the minimum OAuth scopes needed for the integration',
        '- Always set a contact email for ownership traceability',
        '- Prefer named credentials / external client apps over storing secrets in Apex',
        '',
        'See `references/connected-apps-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Connected Apps ({len(apps)})', '']
    for a in apps:
        ref_lines.append(f"### {a.get('label') or a.get('apiName', '')}")
        if a.get('description'):
            ref_lines.append(f"- **Description:** {a['description']}")
        if a.get('contactEmail'):
            ref_lines.append(f"- **Contact email:** {a['contactEmail']}")
        if a.get('scopes'):
            ref_lines.append(f"- **Scopes:** {', '.join(a['scopes'])}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_prompt_template_skill(parsed: dict, config: dict) -> dict:
    templates = parsed.get('templates', [])
    template_types = list(dict.fromkeys(t['templateType'] for t in templates if t.get('templateType')))

    skill_lines = [_frontmatter(
        'salesforce-prompt-templates',
        "Conventions for this org's Prompt Builder / GenAI prompt templates. Use when creating a new Agentforce or Prompt Builder template."
    ).rstrip('\n'), '', '# Prompt templates (Prompt Builder / Agentforce)', '', '## Template types in use']
    skill_lines += [f'- {t}' for t in template_types]
    skill_lines += [
        '',
        '## Design rules for new prompt templates',
        '- Keep grounding/merge-field references explicit and scoped to the fields actually needed',
        '- Give every template a description explaining its business purpose',
        '- Test each template version before activating it',
        '',
        'See `references/prompt-templates-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Prompt templates ({len(templates)})', '']
    for t in templates:
        ref_lines.append(f"### {t.get('masterLabel') or t.get('apiName', '')}")
        if t.get('templateType'):
            ref_lines.append(f"- **Type:** {t['templateType']}")
        if t.get('description'):
            ref_lines.append(f"- **Description:** {t['description']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_flexipage_skill(parsed: dict, config: dict) -> dict:
    pages = parsed.get('pages', [])
    page_types = list(dict.fromkeys(p['type'] for p in pages if p.get('type')))

    skill_lines = [_frontmatter(
        'salesforce-flexipages',
        "Conventions for this org's Lightning pages (FlexiPages). Use when creating a new App Page, Record Page, or Home Page."
    ).rstrip('\n'), '', '# FlexiPages (Lightning App Builder)', '', '## Page types in use']
    skill_lines += [f'- {t}' for t in page_types]
    skill_lines += [
        '',
        '## Design rules for new pages',
        '- Name pages by their purpose and object, e.g. `{Object}_Record_Page`',
        '- Record pages should declare the `sobjectType` they target',
        '- Reuse existing components before building new custom ones',
        '',
        'See `references/flexipages-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: FlexiPages ({len(pages)})', '']
    for p in pages:
        ref_lines.append(f"### {p.get('masterLabel') or p.get('apiName', '')}")
        if p.get('type'):
            ref_lines.append(f"- **Type:** {p['type']}")
        if p.get('sobjectType'):
            ref_lines.append(f"- **Object:** {p['sobjectType']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


def _build_approval_process_skill(parsed: dict, config: dict) -> dict:
    processes = parsed.get('processes', [])
    entities = list(dict.fromkeys(p['entity'] for p in processes if p.get('entity')))

    skill_lines = [_frontmatter(
        'salesforce-approval-processes',
        "Conventions for this org's Approval Processes. Use when creating a new approval process."
    ).rstrip('\n'), '', '# Approval Processes', '', '## Objects with approval processes']
    skill_lines += [f'- {e}' for e in entities]
    skill_lines += [
        '',
        '## Design rules for new approval processes',
        '- Give every process a description explaining when it triggers and why',
        '- Define an explicit rejection/recall path, not just the approval path',
        '- Keep entry criteria narrow enough to avoid unintended submissions',
        '',
        'See `references/approval-processes-reference.md` for the full inventory.',
    ]

    ref_lines = [f'# Reference: Approval Processes ({len(processes)})', '']
    for p in processes:
        ref_lines.append(f"### {p['fullName']}")
        if p.get('label'):
            ref_lines.append(f"- **Label:** {p['label']}")
        ref_lines.append(f"- **Object:** {p['entity']}")
        ref_lines.append(f"- **Active:** {p['active']}")
        if p.get('description'):
            ref_lines.append(f"- **Description:** {p['description']}")
        ref_lines.append('')

    return {'skillMd': '\n'.join(skill_lines) + '\n', 'referenceMd': '\n'.join(ref_lines) + '\n'}


_SKILL_REGISTRY = {
    'objects':              {'skillName': 'salesforce-objects',            'builder': _build_objects_skill},
    'flows':                {'skillName': 'salesforce-flows',              'builder': _build_flows_skill},
    'classes':              {'skillName': 'salesforce-apex',               'builder': _build_apex_skill},
    'triggers':             {'skillName': 'salesforce-apex',               'builder': _build_apex_skill},
    'lwc':                  {'skillName': 'salesforce-lwc',                'builder': _build_lwc_skill},
    'permissionsets':       {'skillName': 'salesforce-permission-sets',    'builder': _build_permset_skill},
    'profiles':              {'skillName': 'salesforce-profiles',           'builder': _build_profile_skill},
    'layouts':               {'skillName': 'salesforce-layouts',            'builder': _build_layout_skill},
    'emailTemplates':        {'skillName': 'salesforce-email-templates',    'builder': _build_template_skill},
    'customMetadata':        {'skillName': 'salesforce-custom-metadata',    'builder': _build_custom_metadata_skill},
    'connectedApps':         {'skillName': 'salesforce-connected-apps',     'builder': _build_connected_app_skill},
    'genAiPromptTemplates':  {'skillName': 'salesforce-prompt-templates',   'builder': _build_prompt_template_skill},
    'flexipages':            {'skillName': 'salesforce-flexipages',         'builder': _build_flexipage_skill},
    'approvalProcesses':     {'skillName': 'salesforce-approval-processes', 'builder': _build_approval_process_skill},
}
