"""
generator.py
Converts parsed metadata objects into Claude-ready Markdown skill files.
Port of scripts/node/generator.js.
"""

from datetime import date


def generate_skill(metadata_type: str, parsed: dict, config: dict) -> str:
    """
    Generate a Markdown skill file from parsed metadata.

    Args:
        metadata_type: e.g. 'objects', 'flows', 'classes'
        parsed: output from the relevant parser
        config: org-config.json contents as dict

    Returns:
        Markdown string
    """
    builders = {
        'objects':        _build_objects_skill,
        'flows':          _build_flows_skill,
        'classes':        _build_apex_skill,
        'triggers':       _build_apex_skill,
        'lwc':            _build_lwc_skill,
        'permissionsets': _build_permset_skill,
        'profiles':       _build_profile_skill,
        'layouts':        _build_layout_skill,
        'emailTemplates': _build_template_skill,
    }

    builder = builders.get(metadata_type)
    if not builder:
        return f'# {metadata_type}\n\nNo skill builder registered for this type.\n'

    return builder(parsed, config)


# ─── BUILDERS ────────────────────────────────────────────────────────────────

def _build_objects_skill(parsed: dict, config: dict) -> str:
    objects = parsed.get('objects', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        f'# Skill: Custom objects & fields',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when creating new custom objects, custom fields, or modifying object metadata to match this org's conventions.",
        '',
        '## Naming conventions',
    ]

    prefixes = list(dict.fromkeys(
        o['apiName'].split('__')[0] for o in objects if o.get('apiName') and '__' in o['apiName']
    ))
    if prefixes:
        lines.append(f"- **Namespace/prefix patterns found:** {', '.join(prefixes)}")

    lines += [
        '- Custom objects end with `__c`',
        '- Custom fields end with `__c`',
        '',
        f'## Objects in this org ({len(objects)})',
        '',
    ]

    for obj in objects:
        lines.append(f"### {obj.get('apiName') or obj.get('label', '')}")
        if obj.get('label'):
            lines.append(f"- **Label:** {obj['label']}")
        if obj.get('description'):
            lines.append(f"- **Description:** {obj['description']}")
        fields = obj.get('fields', [])
        if fields:
            field_types = list(dict.fromkeys(f['type'] for f in fields if f.get('type')))
            lines.append(f"- **Field count:** {len(fields)}")
            lines.append(f"- **Field types used:** {', '.join(field_types)}")
            lines.append('- **Sample fields:**')
            for f in fields[:5]:
                req = ' — required' if f.get('required') else ''
                lines.append(f"  - `{f['apiName']}` ({f.get('type', '')}){req}")
        lines.append('')

    lines += [
        '## Design rules for new objects',
        '- Mirror the naming prefix patterns listed above',
        '- Always include a Description on new objects',
        '- Required fields should be clearly marked',
        '- Lookup fields should follow the pattern: `RelatedObject__c`',
    ]

    return '\n'.join(lines) + '\n'


def _build_flows_skill(parsed: dict, config: dict) -> str:
    flows = parsed.get('flows', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Flows & automations',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when building new Flows, Screen Flows, or Record-Triggered Flows to match this org's structure and naming.",
        '',
        '## Flow types in use',
    ]

    types = list(dict.fromkeys(f['processType'] for f in flows if f.get('processType')))
    for t in types:
        lines.append(f'- {t}')

    names = [f['apiName'] for f in flows if f.get('apiName')]
    lines.append('')
    lines.append('## Naming patterns')
    if names:
        sample = ', '.join(f'`{n}`' for n in names[:8])
        lines.append(f'Examples from this org: {sample}')

    lines += ['', f'## Flows inventory ({len(flows)})', '']

    for flow in flows:
        lines.append(f"### {flow.get('apiName', '')}")
        if flow.get('label'):
            lines.append(f"- **Label:** {flow['label']}")
        if flow.get('processType'):
            lines.append(f"- **Type:** {flow['processType']}")
        if flow.get('triggerType'):
            lines.append(f"- **Trigger:** {flow['triggerType']}")
        if flow.get('object'):
            lines.append(f"- **Object:** {flow['object']}")
        lines.append('')

    lines += [
        '## Design rules for new flows',
        '- Match the naming conventions shown above',
        '- Record-triggered flows should specify trigger type (Before Save / After Save)',
        "- Always add a description explaining the flow's business purpose",
        '- Fault paths should be handled for all DML operations',
    ]

    return '\n'.join(lines) + '\n'


def _build_apex_skill(parsed: dict, config: dict) -> str:
    classes = parsed.get('classes', [])
    triggers = parsed.get('triggers', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Apex classes & triggers',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when writing new Apex classes, trigger handlers, or test classes to match this org's code standards.",
        '',
        '## Class naming conventions',
    ]

    if classes:
        names = [c['name'] for c in classes if c.get('name')]
        sample = ', '.join(f'`{n}`' for n in names[:8])
        lines.append(f'Examples: {sample}')
        lines.append('')
        if any('Handler' in n for n in names):
            lines.append('- Trigger handlers named: `{Object}TriggerHandler`')
        if any('Service' in n for n in names):
            lines.append('- Service classes named: `{Domain}Service`')
        if any('Helper' in n for n in names):
            lines.append('- Helper classes named: `{Domain}Helper`')
        if any(n.endswith('Test') or n.endswith('_Test') for n in names):
            lines.append('- Test classes named: `{ClassName}Test`')

    lines += ['', '## Trigger conventions']
    for t in triggers:
        events = ', '.join(t.get('events', [])) or 'unknown'
        lines.append(f"- `{t['name']}` → object: {t.get('object') or 'unknown'}, events: {events}")

    lines += ['', f'## Classes inventory ({len(classes)})']
    for cls in classes[:20]:
        test_tag = ' [test]' if cls.get('isTest') else ''
        lines.append(f"- `{cls['name']}`{test_tag}")
    if len(classes) > 20:
        lines.append(f'- ... and {len(classes) - 20} more')

    lines += [
        '',
        '## Design rules for new Apex',
        '- One trigger per object — all logic in a handler class',
        '- Bulkify all trigger logic (never query or DML inside loops)',
        '- Test classes must have @isTest annotation and achieve 90%+ coverage',
        '- Use `with sharing` on all new classes unless explicitly required otherwise',
        '- Constants go in a dedicated `Constants` or `{Domain}Constants` class',
    ]

    return '\n'.join(lines) + '\n'


def _build_lwc_skill(parsed: dict, config: dict) -> str:
    components = parsed.get('components', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: LWC components',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when building new Lightning Web Components to match this org's component structure and conventions.",
        '',
        '## Component naming conventions',
        '- camelCase for component folder and files',
    ]

    if components:
        names = [c['name'] for c in components if c.get('name')]
        sample = ', '.join(f'`{n}`' for n in names[:8])
        lines.append(f'- Examples from this org: {sample}')

    lines += ['', f'## Components inventory ({len(components)})', '']

    for cmp in components:
        lines.append(f"### {cmp['name']}")
        if cmp.get('files'):
            lines.append(f"- **Files:** {', '.join(cmp['files'])}")
        if cmp.get('hasApexWire'):
            lines.append('- **Pattern:** Uses @wire with Apex')
        if cmp.get('hasLds'):
            lines.append('- **Pattern:** Uses Lightning Data Service')
        lines.append('')

    lines += [
        '## Design rules for new LWC',
        '- Every component needs: .js, .html, .js-meta.xml',
        '- Use @wire for read operations, imperative Apex for write operations',
        '- Fire events upward, properties downward',
        '- CSS scoped to component — no global styles',
    ]

    return '\n'.join(lines) + '\n'


def _build_permset_skill(parsed: dict, config: dict) -> str:
    permsets = parsed.get('permsets', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Permission sets',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when creating new permission sets to match this org's access model.",
        '',
        f'## Permission sets in this org ({len(permsets)})',
        '',
    ]

    for ps in permsets:
        lines.append(f"### {ps.get('label') or ps.get('apiName', '')}")
        if ps.get('description'):
            lines.append(f"- **Description:** {ps['description']}")
        if ps.get('objectPerms'):
            lines.append(f"- **Object permissions:** {ps['objectPerms']} objects")
        if ps.get('fieldPerms'):
            lines.append(f"- **Field permissions:** {ps['fieldPerms']} fields")
        lines.append('')

    lines += [
        '## Design rules for new permission sets',
        '- Always add a clear description explaining the business role',
        '- Grant minimum required access — never grant Delete unless justified',
        '- Field-level security must be explicitly set for sensitive fields',
    ]

    return '\n'.join(lines) + '\n'


def _build_profile_skill(parsed: dict, config: dict) -> str:
    profiles = parsed.get('profiles', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Profiles',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when modifying profiles or understanding the org's user access model.",
        '',
        f'## Profiles in this org ({len(profiles)})',
    ]

    for p in profiles:
        lines.append(f"- `{p['name']}`")

    lines += [
        '',
        '## Design rules',
        '- Prefer permission sets over profile permissions for feature access',
        '- Profiles define baseline access; permission sets layer on top',
    ]

    return '\n'.join(lines) + '\n'


def _build_layout_skill(parsed: dict, config: dict) -> str:
    layouts = parsed.get('layouts', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Page layouts',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        'Load this skill when creating or modifying page layouts.',
        '',
        f'## Layouts in this org ({len(layouts)})',
    ]

    for l in layouts:
        lines.append(f"- `{l['name']}`")

    lines += [
        '',
        '## Design rules',
        '- Group related fields into sections',
        '- Required fields should appear in the first section',
        '- Use 2-column layout for standard sections',
    ]

    return '\n'.join(lines) + '\n'


def _build_template_skill(parsed: dict, config: dict) -> str:
    templates = parsed.get('templates', [])
    now = date.today().isoformat()
    org_name = config.get('orgName', 'unknown')

    lines = [
        '# Skill: Email templates',
        f'<!-- Generated by sf-claude-context-forge on {now} for org: {org_name} -->',
        '',
        '## When to use this skill',
        "Load this skill when creating new email templates to match this org's tone and structure.",
        '',
        f'## Templates in this org ({len(templates)})',
        '',
    ]

    for t in templates:
        lines.append(f"### {t['name']}")
        if t.get('subject'):
            lines.append(f"- **Subject pattern:** {t['subject']}")
        if t.get('encoding'):
            lines.append(f"- **Encoding:** {t['encoding']}")
        lines.append('')

    lines += [
        '## Design rules for new templates',
        '- Use merge fields for personalization',
        '- Always include a plain-text version',
        '- Subject lines should be clear and action-oriented',
    ]

    return '\n'.join(lines) + '\n'
